#!/usr/bin/env python

import sys

output = open(sys.argv[1], 'w')
data = open(sys.argv[2]).read()

output.write("#include \"rom.h\"\n")
output.write("const uint8_t monitor_rom[] = {\n")

while len(data):
    output.write(", ".join('0x%02x' % ord(x) for x in data[:16]) + ',\n')
    data = data[16:]

output.write("};\n")
