#!/usr/bin/env python

import sys

output = open(sys.argv[1], 'w')
data = open(sys.argv[2]).read()

output.write("#include <avr/pgmspace.h>\n")
output.write("#include <avr/io.h>\n")
output.write("const uint8_t z80_rom[] PROGMEM = {\n")

while len(data):
    output.write(", ".join('0x%02x' % ord(x) for x in data[:16]) + ',\n')
    data = data[16:]

output.write("};\n")
